### ISSUE TITLE
Sign in doesn't work

### ISSUE THREAD

**Issue by anshulkc** [kumarkrishh/PantryPal.ai#90]
./components/EditRecipeCard.tsx
Error:   × Unexpected token `Card`. Expected jsx identifier
     ╭─[/Users/anshulkc/PantryPal35L/pantrypal.ai/components/EditRecipeCard.tsx:157:1]
 154 │   };
 155 │ 
 156 │   return (
 157 │     <Card className="fixed inset-0 z-50 overflow-auto bg-white">
     ·      ────
 158 │       <CardHeader>
 159 │         <CardTitle className="text-2xl">{editedRecipe.title}</CardTitle>
 160 │       </CardHeader>
     ╰────

Caused by:
    Syntax Error

**Comment by aditya-r123** [comment]
it works for me, at least with google login
